version: '3.8'

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8999 planningpoker.asgi:application
    ports:
      - "8999:8999"
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

