version: "3.8"

services:
  planning_poker:
    image: ghcr.io/eren-nere/planning-poker:latest # Remplacez par l'image publiée sur GHCR
    container_name: planning_poker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    command: ["redis-server"]
