# Generated by Django 5.1.3 on 2024-12-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_poker', '0002_pokerroom_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokerroom',
            name='rule',
            field=models.CharField(default='strict', max_length=50),
        ),
    ]
