# Generated by Django 5.1.3 on 2024-12-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_poker', '0004_remove_pokerroom_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokerroom',
            name='mode',
            field=models.CharField(choices=[('unanimite', 'Unanimité'), ('majorite', 'Majorité absolue')], default='unanimite', max_length=20),
        ),
    ]
