# Generated by Django 5.1.3 on 2024-12-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_poker', '0006_pokerroom_backlog_alter_pokerroom_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokerroom',
            name='backlog',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='pokerroom',
            name='mode',
            field=models.CharField(choices=[('unanimity', 'Unanimité'), ('absolute_majority', 'Majorité absolue')], default='unanimity', max_length=20),
        ),
    ]
