# Generated by Django 5.1.3 on 2024-12-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_poker', '0007_alter_pokerroom_backlog_alter_pokerroom_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokerroom',
            name='backlog',
            field=models.TextField(),
        ),
    ]
