# Generated by Django 5.1.3 on 2024-12-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_poker', '0008_alter_pokerroom_backlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokerroom',
            name='all_features',
            field=models.TextField(default='[]'),
        ),
    ]
