name: Générer documentation

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Doxygen 1.12.0
        run: |
          curl -L https://github.com/doxygen/doxygen/releases/download/Release_1_12_0/doxygen-1.12.0.linux.bin.tar.gz -o doxygen.tar.gz
          tar -xzf doxygen.tar.gz
          sudo mv doxygen-1.12.0/bin/doxygen /usr/local/bin/doxygen
          doxygen --version

      - name: Generate Documentation
        run: doxygen

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
