name: Django CI

on:
  push:
    branches:
      - main  # Exécuter les tests sur la branche principale
  pull_request:
    branches:
      - main  # Exécuter les tests sur les pull requests vers la branche principale

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up database
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          pytest --ds=planningpoker.settings
